#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


compton --config /home/r0ck3t/.config/compton/compton.conf &
feh --bg-fill /home/r0ck3t/Pictures/Wallpapers/Dragon.jpg &
~/.config/polybar/launch.sh --forest  &
#redshift -c ~/.config/redshift/redshift.conf &
dunst &

wmname LG3D &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           4

bspc config active_border_color '#d2d2d2'
bspc config normal_border_color '#d2d2d2'
bspc config focused_border_color '#d2d2d2'

bspc config border_radius 9.0
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a jetbrains-studio state=floating
bspc rule -a jetbrains-pycharm-ce state=floating
bspc rule -a jetbrains-idea-ce state=floating
bspc rule -a Eclipse state=floating
bspc rule -a Java state=floating
bspc rule -a Audacious state=floating
bspc rule -a Brackets state=tiled
bspc rule -a Steam state=floating
bspc rule -a Anki:anki state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Pulseaudio-equalizer-gtk state=floating
